version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: operationaldb
      MYSQL_MAX_CONNECTIONS: 10000
    expose:
      - 3306
    networks:
      - my-network
    command: --max-connections=10000
    healthcheck:
      test: [ "CMD", "bash", "-c", "if [ -z $$(mysqladmin -h localhost ping 2>/dev/null) ]; then exit 1; fi" ]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 10s

  blazegraph:
    image: conjecto/blazegraph
    container_name: blazegraph
    environment:
      JAVA_OPTS: "-Xms512m -Xmx2g"
    volumes:
      - ./blazegraph-data:/var/lib/blazegraph
      - ./data:/docker-entrypoint-initdb.d/kb/data
    ports:
      - "9999:9999"
    expose:
      - 9999
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "bash", "-c", "curl -f http://localhost:9999/blazegraph/ || exit 1" ]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 15s

#  blockscanner1:
#    image: alethio/ethereum-lite-explorer
#    container_name: blockscanner1
#    ports:
#      - "8080:80"  # Accessible at http://localhost:8080
#    environment:
#      - APP_NODE_URL=http://localhost:8545
#    networks:
#      - my-network
#    depends_on:
#      - dkg-evm-module
#
#  blockscanner2:
#    image: alethio/ethereum-lite-explorer
#    container_name: blockscanner2
#    ports:
#      - "8081:80"  # Accessible at http://localhost:8081
#    environment:
#      - APP_NODE_URL=http://localhost:9545
#    networks:
#      - my-network
#    depends_on:
#      - dkg-evm-module

  dkg-evm-module:
    build:
      context: .
      dockerfile: dkg-evm-module.Dockerfile
    container_name: hardhat-network
    ports:
      - "8545:8545"  # ot-node-docker application port
      - "9545:9545"  # ot-node-docker application port
    volumes:
      - ./dkg-evm-module:/app
      - dkg_node_modules:/app/node_modules
      - dkg_hardhat_cache:/app/cache
      - dkg_hardhat_data:/app/.hardhat
    expose:
      - 8545
      - 9545
    working_dir: /app/dkg-evm-module
    command: >
      /bin/sh -c "
      npm run dev:v1 -- --port 8545 &
      npm run dev:v1 -- --port 9545 &
      wait
      "
    networks:
      - my-network

  ot-node:
    build:
      context: .
      dockerfile: ot-node.Dockerfile
    container_name: ot-node
    ports:
      - "8900:8900"  # ot-node-docker application port
    environment:
      - NODE_ENV=development
    networks:
      - my-network
    depends_on:
      - mysql
      - blazegraph
      - dkg-evm-module
    working_dir: /app/ot-node-docker  # Ensure the working directory is set to /app/ot-node-docker
    entrypoint: [ "/bin/sh", "-c", "/bin/sleep 25 && chmod +x ./tools/local-network-setup/setup-linux-environment.sh && ./tools/local-network-setup/setup-linux-environment.sh --nodes=8" ]

#  ui:
#    build:
#      context: .
#      dockerfile: ui.Dockerfile
#    container_name: ui
#    ports:
#      - "4200:4200"
#    working_dir: /app/ui
#    depends_on:
#      - ot-node
#      - dkg-evm-module
#    command: ["npm", "start"]
#    networks:
#      - my-network
networks:
  my-network:
    driver: bridge

volumes:
  dkg_node_modules:
  dkg_hardhat_cache:
  dkg_hardhat_data: